### ISSUE TITLE
Working with Acer Swift Go 14 SFG14-71

### ISSUE THREAD

**Issue by TID41** [enielrodriguez/acer-battery-limit-switcher#3]
The plasmoid is working very nicely with the acer-wmi-battery driver on my Acer Swift Go 14 SFG14-71 laptop. It stops charging at 80% like it is meant to with the saver mode on, and the calibrate feature does properly trigger that mode too. The tray icon accurately reflects the state of the laptop in terms of that mode. Thanks for a handy tool!

I would suggest that you add a line to the description in the KDE Store page stating that the acer-wmi-battery driver is needed for the plasmoid to work. I tried using the plasmoid without the driver at first (I thought perhaps the existing acer-wmi driver would work), and of course it did not work. Once I found and used the acer-wmi-battery driver, it worked perfectly.

If you wish to make one for Dell (especially using the CCTK backend, as I was not able yet to get the other one working), I would be happy to test it on my XPS (9310).

**Comment by enielrodriguez** [comment]
I just added the driver requirement in the description.  
When I have some time I will evaluate adapting the widget for Dell laptops.  
Thank you very much for your feedback!

**Comment by enielrodriguez** [comment]
Hi! How are you?!  
I already made a first version for Dell based on CCTK 
KDE Store: [CCTK BatteryCfg](https://www.pling.com/p/2097829/)  
Github: [CCTK BatteryCfg](https://github.com/enielrodriguez/cctk-batterycfg) 
Could you try it and tell me if it works?

**Comment by TID41** [comment]
The most recent versions of this widget (the Acer one) do not work correctly. In main.qml, a comma at the end of the line is missing on line 93. This causes a syntax error when I try to open the applet. 

Also, the metadata file still shows version 1.0.1 even though it is listed as 1.0.2 on the KDE site.

**Comment by enielrodriguez** [comment]
Hello! Thanks, I'll check it out as soon as possible.
